---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: kafka
spec:
  encryptedData:
    aws-credentials.properties: AgB8wzpuyPPd58UzYFySnStzY3KX0mQSJBDDrPJS2MOCm2yjGj1dKtHLS8QyMZKIyHWI68b0bMNBSliwNb4h9UlubqtFHU7QuMy31YuppHSu7yWtobOXu6DQK4Xup3vahYw/mU+HVCr8ESO4R3mNzn5W3sWfIYzWMxuV7qCGp0XmF715zZsMcMmRpYjnA+bIcPvgFV9InUVBKZzFDu7hyuRXFztYgDz5w8iWT7S/VcDP/wv2XPNOgzILBsRB3HW1ZWpjQoCcD1SZ0ZLa/Cl9sE7qXN0PN+4vE43BGRnQaTICu4Lfj6ZyOlwFBmfXXL5Sanr9uFsYDy9CYyVoBPXx6uNqYvpowdo8Cpmzs0oc/E2gslxp8ULUdrXjzoGn82lYgEcs37uBVmhbk/O93Q7FQ8WOi3Cz2McSk5a22Ag5NljlcEcMPRkb6nCrjOhBTLKqXmGaafltgN5ATIrAa6gUq0cTrtoLalVo2/CE7L3Mr7hZ0br2LJtgw9ASctvY6N6HI3jJWOLLnhngC+vOAFwLs5BGX926F4opohKlVzA/z9EVCoVPybWLpI6VghAyJpASPScpOnTxEenSY6h83RRXWoq04uTA1iEx/9MQE8GSLqkPN/k/3WqjTP5Pf3cQBm0AKnpHpXBiksh+b4L4qF15L0QyGHXHJ8r8CcBcoI9x1/UiXOzVm1lWZ0JVg6vnZKyvK8Yst02pHsSYP/X3j8Eb8YnmXPN6ubeHiLVibcNpO8le9qMr9IpJQQA1SFCe/f5ZIzdZVjJioNpVcewokJlw9bIra8r84xVG78C9tnCpGcsCxuOz0wtto/pnT4l48446
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: kafka
    type: Opaque
